-- Word Bank: gabarito e rastreamento de domínio
ALTER TABLE public.spn_word_bank_items
  ADD COLUMN IF NOT EXISTS translation_pt text,
  ADD COLUMN IF NOT EXISTS accepted_answers text[] NOT NULL DEFAULT '{}';

ALTER TABLE public.spn_word_translations
  ADD COLUMN IF NOT EXISTS attempts integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS correct_streak integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_mastered boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_attempt_at timestamptz;

WITH seed(w, tr, alts) AS (
  VALUES
('hello', 'olá', ARRAY['oi','alô']::text[]),
('hi', 'oi', ARRAY['olá']::text[]),
('goodbye', 'tchau', ARRAY['adeus','até logo']::text[]),
('bye', 'tchau', ARRAY['até mais']::text[]),
('good morning', 'bom dia', ARRAY[]::text[]),
('good afternoon', 'boa tarde', ARRAY[]::text[]),
('good evening', 'boa noite', ARRAY['boa tarde']::text[]),
('good night', 'boa noite', ARRAY[]::text[]),
('name', 'nome', ARRAY[]::text[]),
('nice', 'legal', ARRAY['bom','agradável','gentil']::text[]),
('meet', 'conhecer', ARRAY['encontrar']::text[]),
('you', 'você', ARRAY['tu','vocês']::text[]),
('i', 'eu', ARRAY[]::text[]),
('am', 'sou', ARRAY['estou']::text[]),
('please', 'por favor', ARRAY[]::text[]),
('thanks', 'obrigado', ARRAY['valeu','obrigada']::text[]),
('thank you', 'obrigado', ARRAY['obrigada','muito obrigado']::text[]),
('sorry', 'desculpa', ARRAY['desculpe','perdão','sinto muito']::text[]),
('yes', 'sim', ARRAY[]::text[]),
('no', 'não', ARRAY[]::text[]),
('he', 'ele', ARRAY[]::text[]),
('she', 'ela', ARRAY[]::text[]),
('it', 'isto', ARRAY['isso','ele','ela']::text[]),
('we', 'nós', ARRAY['a gente']::text[]),
('they', 'eles', ARRAY['elas']::text[]),
('man', 'homem', ARRAY[]::text[]),
('woman', 'mulher', ARRAY[]::text[]),
('boy', 'menino', ARRAY['garoto']::text[]),
('girl', 'menina', ARRAY['garota']::text[]),
('person', 'pessoa', ARRAY[]::text[]),
('people', 'pessoas', ARRAY['gente']::text[]),
('friend', 'amigo', ARRAY['amiga']::text[]),
('teacher', 'professor', ARRAY['professora']::text[]),
('student', 'estudante', ARRAY['aluno','aluna']::text[]),
('dog', 'cachorro', ARRAY['cão','cadela']::text[]),
('cat', 'gato', ARRAY['gata']::text[]),
('book', 'livro', ARRAY[]::text[]),
('car', 'carro', ARRAY[]::text[]),
('is', 'é', ARRAY['está']::text[]),
('are', 'são', ARRAY['está','estão','é']::text[]),
('not', 'não', ARRAY[]::text[]),
('happy', 'feliz', ARRAY['contente','alegre']::text[]),
('sad', 'triste', ARRAY[]::text[]),
('tired', 'cansado', ARRAY['cansada']::text[]),
('hungry', 'com fome', ARRAY['faminto']::text[]),
('thirsty', 'com sede', ARRAY[]::text[]),
('busy', 'ocupado', ARRAY['ocupada']::text[]),
('ready', 'pronto', ARRAY['pronta']::text[]),
('late', 'atrasado', ARRAY['atrasada','tarde']::text[]),
('here', 'aqui', ARRAY[]::text[]),
('there', 'lá', ARRAY['ali','aí']::text[]),
('home', 'casa', ARRAY['lar']::text[]),
('school', 'escola', ARRAY['colégio']::text[]),
('work', 'trabalho', ARRAY['trabalhar']::text[]),
('brazilian', 'brasileiro', ARRAY['brasileira']::text[]),
('english', 'inglês', ARRAY['inglesa']::text[]),
('eat', 'comer', ARRAY[]::text[]),
('drink', 'beber', ARRAY['tomar']::text[]),
('want', 'querer', ARRAY['quero']::text[]),
('like', 'gostar', ARRAY['gosto']::text[]),
('play', 'jogar', ARRAY['brincar','tocar']::text[]),
('go', 'ir', ARRAY[]::text[]),
('have', 'ter', ARRAY['tenho','tem']::text[]),
('see', 'ver', ARRAY['enxergar']::text[]),
('read', 'ler', ARRAY[]::text[]),
('write', 'escrever', ARRAY[]::text[]),
('speak', 'falar', ARRAY[]::text[]),
('listen', 'ouvir', ARRAY['escutar']::text[]),
('study', 'estudar', ARRAY[]::text[]),
('sleep', 'dormir', ARRAY[]::text[]),
('run', 'correr', ARRAY[]::text[]),
('walk', 'caminhar', ARRAY['andar']::text[]),
('come', 'vir', ARRAY[]::text[]),
('need', 'precisar', ARRAY['necessitar']::text[]),
('know', 'saber', ARRAY['conhecer']::text[]),
('a', 'um', ARRAY['uma']::text[]),
('an', 'um', ARRAY['uma']::text[]),
('the', 'o', ARRAY['a','os','as']::text[]),
('apple', 'maçã', ARRAY[]::text[]),
('orange', 'laranja', ARRAY[]::text[]),
('water', 'água', ARRAY[]::text[]),
('juice', 'suco', ARRAY[]::text[]),
('coffee', 'café', ARRAY[]::text[]),
('tea', 'chá', ARRAY[]::text[]),
('bread', 'pão', ARRAY[]::text[]),
('rice', 'arroz', ARRAY[]::text[]),
('chicken', 'frango', ARRAY['galinha']::text[]),
('table', 'mesa', ARRAY[]::text[]),
('chair', 'cadeira', ARRAY[]::text[]),
('door', 'porta', ARRAY[]::text[]),
('window', 'janela', ARRAY[]::text[]),
('house', 'casa', ARRAY[]::text[]),
('phone', 'telefone', ARRAY['celular']::text[]),
('computer', 'computador', ARRAY[]::text[]),
('pen', 'caneta', ARRAY[]::text[]),
('my', 'meu', ARRAY['minha']::text[]),
('your', 'seu', ARRAY['sua','teu','tua']::text[]),
('his', 'dele', ARRAY['seu']::text[]),
('her', 'dela', ARRAY['sua']::text[]),
('its', 'dele', ARRAY['dela','seu']::text[]),
('our', 'nosso', ARRAY['nossa']::text[]),
('their', 'deles', ARRAY['delas']::text[]),
('father', 'pai', ARRAY[]::text[]),
('mother', 'mãe', ARRAY[]::text[]),
('brother', 'irmão', ARRAY[]::text[]),
('sister', 'irmã', ARRAY[]::text[]),
('son', 'filho', ARRAY[]::text[]),
('daughter', 'filha', ARRAY[]::text[]),
('job', 'trabalho', ARRAY['emprego']::text[]),
('do', 'fazer', ARRAY['faço']::text[]),
('does', 'faz', ARRAY[]::text[]),
('don''t', 'não', ARRAY['nao']::text[]),
('doesn''t', 'não', ARRAY['nao']::text[]),
('every', 'todo', ARRAY['toda','cada']::text[]),
('always', 'sempre', ARRAY[]::text[]),
('usually', 'geralmente', ARRAY['normalmente']::text[]),
('often', 'frequentemente', ARRAY['muitas vezes']::text[]),
('sometimes', 'às vezes', ARRAY['as vezes']::text[]),
('never', 'nunca', ARRAY['jamais']::text[]),
('morning', 'manhã', ARRAY[]::text[]),
('afternoon', 'tarde', ARRAY[]::text[]),
('night', 'noite', ARRAY[]::text[]),
('weekend', 'fim de semana', ARRAY[]::text[]),
('breakfast', 'café da manhã', ARRAY[]::text[]),
('lunch', 'almoço', ARRAY[]::text[]),
('dinner', 'jantar', ARRAY[]::text[]),
('watch', 'assistir', ARRAY['ver']::text[]),
('tv', 'televisão', ARRAY['tv']::text[]),
('music', 'música', ARRAY[]::text[]),
('what', 'o que', ARRAY['que','qual']::text[]),
('where', 'onde', ARRAY[]::text[]),
('when', 'quando', ARRAY[]::text[]),
('who', 'quem', ARRAY[]::text[]),
('why', 'por que', ARRAY['porque','porquê']::text[]),
('how', 'como', ARRAY[]::text[]),
('which', 'qual', ARRAY['quais']::text[]),
('how much', 'quanto', ARRAY['quanto custa']::text[]),
('how many', 'quantos', ARRAY['quantas']::text[]),
('how old', 'quantos anos', ARRAY['que idade']::text[]),
('because', 'porque', ARRAY[]::text[]),
('answer', 'resposta', ARRAY['responder']::text[]),
('question', 'pergunta', ARRAY['questão']::text[]),
('live', 'morar', ARRAY['viver']::text[]),
('from', 'de', ARRAY['desde']::text[]),
('now', 'agora', ARRAY[]::text[]),
('today', 'hoje', ARRAY[]::text[]),
('tomorrow', 'amanhã', ARRAY[]::text[]),
('yesterday', 'ontem', ARRAY[]::text[]),
('country', 'país', ARRAY[]::text[]),
('in', 'em', ARRAY['no','na','dentro']::text[]),
('on', 'em', ARRAY['sobre','no','na']::text[]),
('at', 'em', ARRAY['no','na','às']::text[]),
('with', 'com', ARRAY[]::text[]),
('without', 'sem', ARRAY[]::text[]),
('for', 'para', ARRAY['por']::text[]),
('to', 'para', ARRAY['a','ao']::text[]),
('of', 'de', ARRAY['do','da']::text[]),
('and', 'e', ARRAY[]::text[]),
('but', 'mas', ARRAY['porém']::text[]),
('or', 'ou', ARRAY[]::text[]),
('so', 'então', ARRAY['portanto','logo']::text[]),
('also', 'também', ARRAY['tambem']::text[]),
('too', 'também', ARRAY['tambem','demais']::text[]),
('under', 'embaixo', ARRAY['debaixo','sob']::text[]),
('over', 'sobre', ARRAY['em cima','acima']::text[]),
('between', 'entre', ARRAY[]::text[]),
('near', 'perto', ARRAY['próximo']::text[]),
('one', 'um', ARRAY['uma']::text[]),
('two', 'dois', ARRAY['duas']::text[]),
('three', 'três', ARRAY[]::text[]),
('four', 'quatro', ARRAY[]::text[]),
('five', 'cinco', ARRAY[]::text[]),
('ten', 'dez', ARRAY[]::text[]),
('twenty', 'vinte', ARRAY[]::text[]),
('hundred', 'cem', ARRAY['cento']::text[]),
('monday', 'segunda', ARRAY['segunda-feira']::text[]),
('tuesday', 'terça', ARRAY['terça-feira','terca']::text[]),
('wednesday', 'quarta', ARRAY['quarta-feira']::text[]),
('thursday', 'quinta', ARRAY['quinta-feira']::text[]),
('friday', 'sexta', ARRAY['sexta-feira']::text[]),
('saturday', 'sábado', ARRAY[]::text[]),
('sunday', 'domingo', ARRAY[]::text[]),
('day', 'dia', ARRAY[]::text[]),
('week', 'semana', ARRAY[]::text[]),
('month', 'mês', ARRAY[]::text[]),
('year', 'ano', ARRAY[]::text[]),
('o''clock', 'em ponto', ARRAY['horas']::text[]),
('family', 'família', ARRAY[]::text[]),
('dad', 'pai', ARRAY['papai']::text[]),
('mom', 'mãe', ARRAY['mamãe']::text[]),
('parents', 'pais', ARRAY[]::text[]),
('husband', 'marido', ARRAY['esposo']::text[]),
('wife', 'esposa', ARRAY['mulher']::text[]),
('uncle', 'tio', ARRAY[]::text[]),
('aunt', 'tia', ARRAY[]::text[]),
('cousin', 'primo', ARRAY['prima']::text[]),
('grandfather', 'avô', ARRAY['vovô']::text[]),
('grandmother', 'avó', ARRAY['vovó']::text[]),
('baby', 'bebê', ARRAY['neném']::text[]),
('child', 'criança', ARRAY['filho']::text[]),
('children', 'crianças', ARRAY['filhos']::text[]),
('love', 'amar', ARRAY['adorar']::text[]),
('hate', 'odiar', ARRAY['detestar']::text[]),
('prefer', 'preferir', ARRAY[]::text[]),
('enjoy', 'aproveitar', ARRAY['curtir','gostar']::text[]),
('favorite', 'favorito', ARRAY['favorita','preferido']::text[]),
('color', 'cor', ARRAY[]::text[]),
('food', 'comida', ARRAY['alimento']::text[]),
('movie', 'filme', ARRAY[]::text[]),
('song', 'música', ARRAY['canção']::text[]),
('sport', 'esporte', ARRAY[]::text[]),
('really', 'realmente', ARRAY['mesmo','muito']::text[]),
('very much', 'muito', ARRAY[]::text[]),
('a lot', 'muito', ARRAY['bastante']::text[]),
('a little', 'um pouco', ARRAY['pouco']::text[]),
('at all', 'de jeito nenhum', ARRAY['nem um pouco']::text[]),
('kind of', 'meio que', ARRAY['mais ou menos']::text[]),
('pizza', 'pizza', ARRAY[]::text[]),
('chocolate', 'chocolate', ARRAY[]::text[]),
('game', 'jogo', ARRAY[]::text[])
)
UPDATE public.spn_word_bank_items i
SET translation_pt = s.tr,
    accepted_answers = s.alts
FROM seed s
WHERE lower(i.word) = s.w
  AND (i.translation_pt IS NULL OR i.translation_pt = '');